export const EventCategoryList = [
  {
    id: 1,
    title: "Visual Arts",
    url: "visual-arts",
    img: "events/photography.jpg",
  },
  {
    id: 2,
    title: "Performing Arts",
    url: "performing-arts",
    img: "events/dance.jpg",
  },
  {
    id: 3,
    title: "Musical Arts",
    url: "muzical-arts",
    img: "events/music.jpg",
  },
  {
    id: 4,
    title: "Game Zone",
    url: "gaming-zone",
    img: "events/gaming.jpg",
  },
  {
    id: 5,
    title: "Others",
    url: "others",
    img: "events/other.jpg",
  },
];

export const VisualEvents = [
  {
    event: "Live Photography",
    time: "9:00 am onwards, Both Days",
    venue: "Campus",
    image: "",
    url: "photography",
  },
  {
    event: "30 Sec Reels Making Competition",
    time: "9:00 am onwards, Both Days",
    venue: "Campus",
    image: "",
    url: "reel-making",
  },
  {
    event: "Wall Painting (Theme- Beautiful Kashmir)",
    time: "9:00 am, Day-1",
    venue: "Compound Wall",
    image: "",
    url: "wall-painting",
  },
  {
    event: "Face Painting",
    time: "9:00 am, Day-1",
    venue: "LH",
    image: "",
    url: "face-painting",
  },
  {
    event: "Stone Painting",
    time: "9:00 am, Day-1",
    venue: "LH",
    image: "",
    url: "",
  },
  {
    event: "Portrait Sketching",
    time: "2:00 pm, Day-1",
    venue: "DH-3",
    image: "",
    url: "",
  },
  {
    event: "Clay Art",
    time: "2:00 pm, Day-1",
    venue: "LH",
    image: "",
    url: "",
  },
  {
    event: "Wall Painting (Theme - Festival of India)",
    time: "9:00 am, Day-2",
    venue: "Compound Wall",
    image: "",
    url: "",
  },
  {
    event: "Meme Making",
    time: "3:30 pm, Day-2",
    venue: "HT-1",
    image: "",
    url: "",
  },
];

export var MuzicalEvents = [
  {
    event: "Solo Song Eastern",
    time: "2:00 pm, Day-1",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Solo Song Western",
    time: "10:15 am, Day-2",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Solo Regional Instrumental",
    time: "11:30 am, Day-1",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Duet Song",
    time: "2:00 pm, Day-1",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Rap",
    time: "12:30 pm, Day-1",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Battle Of Bands",
    time: "6:00 pm, Day-1",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "BeatBox",
    time: "11:30 am, Day-2",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Ladi Shah (Story telling )",
    time: "1:30 pm, Day-2",
    venue: "HT-2",
    image: "",
    url: "",
  },
  {
    event: "Acapella (Group Singing)",
    time: "3:00 pm, Day-2",
    venue: "Main Stage",
    image: "",
    url: "",
  },
];

export var gamingEvents = [
  {
    event: "Gaming Zone",
    time: "9:00 am, Both Days",
    venue: "PF",
    image: "",
    url: "",
  },
];

export var OtherEvents = [
  {
    event: "The Trained Cuisine (North)",
    time: "9:00 am, Day-1",
    venue: "Workshop",
    image: "",
    url: "",
  },
  {
    event: "Paper Mache Studio",
    time: "1:00 pm, Day-1",
    venue: "DH-2",
    image: "",
    url: "",
  },
  {
    event: "Willow Wicker Studio",
    time: "3:30 pm, Day-1",
    venue: "DH-2",
    image: "",
    url: "",
  },
  {
    event: "Origami Studio",
    time: "9:00 am, Day-2",
    venue: "DH-2",
    image: "",
    url: "",
  },
  {
    event: "The Trained Cuisine (South)",
    time: "11.30 am, Day-2",
    venue: "Workshop",
    image: "",
    url: "",
  },
  {
    event: "Tattoo Making Studio",
    time: "3.30 pm, Day-2",
    venue: "DH-2",
    image: "",
    url: "",
  },
];

export const PerformingEvents = [
  {
    event: "Open Mic",
    time: "10:15 am, Day-2",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Standup Comedy",
    time: "9:30 am, Day-1",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Mushaira/ Shayari",
    time: "11:10 am, Day-1",
    venue: "HT-3",
    image: "",
    url: "",
  },
  {
    event: "Theatrics",
    time: "11:00 am, Day-1",
    venue: "PF",
    image: "",
    url: "",
  },
  {
    event: "Monoacting",
    time: "11:30 am, Day-1",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Drama",
    time: "10:30 am, Day-2",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Mr and Ms Cultural Fest",
    time: "Day-1: Round-1(2:30 pm), Day-2: Finale(5:00 pm)",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Choreonight",
    time: "6.30 pm, Day-2",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Solo Dance (Eastern)",
    time: "3:00 pm, Day-1",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Duet Free Style Dance",
    time: "4:30 pm, Day-1",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Mimicry",
    time: "9:30 am, Day-2",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Meme Making",
    time: "3.30 pm, Day-2",
    venue: "HT-1",
    image: "",
    url: "",
  },
  {
    event: "Drama",
    time: "10:30 am, Day-2",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Mr and Ms Cultural Fest",
    time: "Day-1: Round-1(2:30 pm), Day-2: Finale(5:00 pm)",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Choreonight",
    time: "6.30 pm, Day-2",
    venue: "Main Stage",
    image: "",
    url: "",
  },
];

export const day1Events = [
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
];


export const day2Events = [
  {
    title: "30 sec reel making",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
];
